apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-analytics.fullname" . }}-config
  labels:
    {{- include "api-analytics.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.backend.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
