{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api-analytics.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "api-analytics.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "api-analytics.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}
