apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "api-analytics.fullname" . }}-postgres
  labels:
    {{- include "api-analytics.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "api-analytics.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "api-analytics.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "api-analytics.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-analytics.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-analytics.fullname" . }}-postgres
  labels:
    {{- include "api-analytics.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "api-analytics.fullname" . }}-postgres
  ports:
    - port: 5432
