apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-analytics.fullname" . }}-secret
  labels:
    {{- include "api-analytics.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgres.username }}:{{ .Values.secrets.postgresPassword }}@{{ include "api-analytics.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
  REDIS_URL: "redis://{{ include "api-analytics.fullname" . }}-redis:6379/0"
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
